#
# Travis Setup
#

# faster builds on new travis setup not using sudo
sudo: false
# Ubuntu Xenial 16.04 as the default Travis CI build environment
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
#dist: bionic
language: php

php:
  - 7.4
  - 8.0
#  - nightly

matrix:
  fast_finish: true

allow_failures:
  - php: nightly

branches:
  only:
    - master
    - branch-v1


services:
  - redis-server

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

#before_install:
#  - sudo apt-get -qq update

install:
  - |
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - travis_retry composer self-update && composer --version && command -v composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction
#  - if [ $TRAVIS_PHP_VERSION = 'nightly' ]; then travis_retry composer install --prefer-dist --no-interaction --ignore-platform-reqs; else  composer install; fi


before_script:
  # show some versions and env information
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  - echo 'memory_limit = 64M' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - php -r "echo ini_get('memory_limit').PHP_EOL;"
  #  redis-5.3.2 released(2020-10-22)
  #- if [ `php -v |sed '2,$d'|awk '{print $2}'|awk -F '.' '{print $1}' ` -eq 8 ] ; then no | pecl install redis; else echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
#  -  no | pecl install redis-5.3.2RC2
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  # ensure no files contain UTF-8 byte order mark
  - if ! grep -rlI $'\xEF\xBB\xBF' src/ ; then echo "no utf8 BOM found"; else echo "found utf8 BOM in some files. See above."; exit 1; fi
  # validate composer.json
  - composer validate --no-check-lock
  - pear version
#  - pear run-tests tests/phpt/FileUploadTest.phpt -v
  - php -S localhost:8080 tests/route.php > /dev/null 2>&1 &
  # run PHPUnit
  - ./vendor/bin/phpunit --verbose
  - ./vendor/bin/phpunit --verbose --bootstrap tests/bootstrap_with_errorhandler.php

after_success:
 - travis_retry php vendor/bin/php-coveralls -v
